package bundler

const bundleTemplate = `// Code generated by github.com/reederc42/go-file-bundler DO NOT EDIT.
package {{.Package}}

var {{.Name}} = {{.Value}}
`

const bundleWithViperTemplate = `// Code generated by github.com/reederc42/go-file-bundler DO NOT EDIT.
package {{.Package}}

import "github.com/spf13/viper"

var {{.Name}} = {{.Value}}

func init() {
	for k, v := range {{.Name}} {
		viper.Set(k, v)
	}
}
`
